services:
  db:
    image: mongo
    volumes:
    - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=belosh_mongo
      - MONGO_INITDB_ROOT_PASSWORD=npfanal2025
    ports:
      - 27018:27017

  db-browser:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=belosh_mongo
      - ME_CONFIG_MONGODB_ADMINPASSWORD=npfanal2025
      - ME_CONFIG_MONGODB_URL=mongodb://belosh_mongo:npfanal2025@db:27017/
    depends_on:
      - db
  
  backend:
    build: ./backend
    image: backend
    ports:
      - 3000:3000
    depends_on:
      - db